### ISSUE TITLE
GTP missing from table

### ISSUE THREAD

**Issue by saglag** [swharden/LJPcalc#13]
Guanosine-5'-triphosphate is currently not listed in the ion table

**Comment by swharden** [comment]
I noticed that 😝 

Do you know what it is? It would be awesome if you could add it (with a reference) to the bottom of [src/IonTable.md](https://github.com/swharden/LJPcalc/blob/master/src/IonTable.md) then make a pull request for the change

**Comment by saglag** [comment]
Currently looking around!

**Comment by swharden** [comment]
> Currently looking around!

If we can't find a source, perhaps we can presume it's the same as ATP? (0.15 that of K+)

![image](https://user-images.githubusercontent.com/4165489/75371924-9d42e600-5895-11ea-80c0-adaa537e7fce.png)

We should also add an "add ion", or "ion table details" button below the ion table in the program (#15). If the user clicks it it will launch the website ([IonTable.md](https://github.com/swharden/LJPcalc/blob/master/src/IonTable.md)). This way the user is pointed to help and documentation if they try to add an ion they can't find in the list.

**Comment by saglag** [comment]
I think that's fair, but would have to make a big note /popup when used in
the calculator. A few I've come across treat it as 0 since the
concentration is so low.

**Comment by swharden** [comment]
> I think that's fair, but would have to make a big note /popup when used in the calculator. A few I've come across treat it as 0 since the concentration is so low.

Probably could remove ATP from the list for this reason as well...

_or_ what if we add GTP (and glucose) to the list and set its conductivity to zero? Maybe zero-conductivity ions should pop up a note reminding the user that they probably affect LJP meaningfully, but their presence in the list would let them know that they aren't missing by accident 🤔

**Comment by saglag** [comment]
I like that!

**Comment by swharden** [comment]
I added a few common large and/or low-mobility molecules such as GTP, sucrose, and glucose. They appear in the ion table now, but if a user goes to use one they are notified ~~that they don't know what an ion is~~ that molecules with no charge or low mobility have little effect on LJP so they don't have to be added to the ion set.

![image](https://user-images.githubusercontent.com/4165489/77977998-f22baf00-72ce-11ea-9182-cfaec1ec9782.png)

![image](https://user-images.githubusercontent.com/4165489/77978208-72521480-72cf-11ea-9d93-76dde7fa3313.png)
